name: rewardly
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Firebase
  firebase_core: ^3.4.0
  firebase_auth: ^5.2.0
  cloud_firestore: ^5.4.0
  firebase_remote_config: ^5.1.0
  google_sign_in: ^6.2.1
  firebase_analytics: ^11.1.0

  # State Management
  provider: ^6.1.5+1

  # Ads
  google_mobile_ads: ^5.1.0

  # PDF Export
  pdf: ^3.11.0
  path_provider: ^2.1.3
  widgets_to_image: ^2.0.1

  # Other
  share_plus: ^11.1.0
  google_fonts: ^6.3.1
  intl: ^0.19.0
  go_router: ^16.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.11

flutter:
  uses-material-design: true
  assets:
    - assets/images/
