
// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
///
/// ```dart
/// import 'package:firebase_core/firebase_core.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEcHbPipoI5E6JWvp45sBDy4D_pXjOL6A',
    appId: '1:216522508911:android:2c8560b9e21fb0e9c29b9a',
    messagingSenderId: '216522508911',
    projectId: 'rewardly-6b81d',
    databaseURL: 'https://rewardly-6b81d-default-rtdb.firebaseio.com',
    storageBucket: 'rewardly-6b81d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCq0jQuWYPqCGUtbPTneih0GHfUyVmWpK4',
    appId: '1:216522508911:ios:f4ebaaeb812df8a1c29b9a',
    messagingSenderId: '216522508911',
    projectId: 'rewardly-6b81d',
    databaseURL: 'https://rewardly-6b81d-default-rtdb.firebaseio.com',
    storageBucket: 'rewardly-6b81d.firebasestorage.app',
    iosBundleId: 'com.supreet.rewardly',
  );

}